CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MIGRATION_ID` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `PRODUCT_VERSION` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EF_MIGRATIONS_HISTORY` PRIMARY KEY (`MIGRATION_ID`)
) CHARACTER SET=utf8mb4;

START TRANSACTION;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251014005605_InitialCreate') THEN

    ALTER DATABASE CHARACTER SET utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251014005605_InitialCreate') THEN

    CREATE TABLE `ROLE` (
        `ID` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        `NAME` VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
        `CODE` CHAR(1) CHARACTER SET utf8mb4 NOT NULL,
        `UPDATED_DATE` DATETIME NOT NULL,
        CONSTRAINT `PK_ROLE` PRIMARY KEY (`ID`)
    ) CHARACTER SET=utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251014005605_InitialCreate') THEN

    CREATE TABLE `USER` (
        `ID` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        `NAME` VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
        `EMAIL` VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
        `HASH` VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
        `UPDATED_DATE` DATETIME NOT NULL,
        CONSTRAINT `PK_USER` PRIMARY KEY (`ID`)
    ) CHARACTER SET=utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251014005605_InitialCreate') THEN

    CREATE TABLE `USER_ROLE` (
        `ID` char(36) COLLATE ascii_general_ci NOT NULL,
        `ID_USER` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        `ID_ROLE` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        CONSTRAINT `PK_USER_ROLE` PRIMARY KEY (`ID`),
        CONSTRAINT `FK_USER_ROLE_USER_ID_USER` FOREIGN KEY (`ID_USER`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
    ) CHARACTER SET=utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251014005605_InitialCreate') THEN

    INSERT INTO `ROLE` (`ID`, `CODE`, `NAME`, `UPDATED_DATE`)
    VALUES ('070e6e2c-2341-4db0-bf29-0e10308ec5a6', 'U', 'USER', TIMESTAMP '2025-10-13 21:56:02'),
    ('70fc65db-de17-4cab-a175-159ab2196f59', 'A', 'ADMIN', TIMESTAMP '2025-10-13 21:56:02'),
    ('9300941a-a3eb-46c6-8a30-81c321c14ade', 'M', 'MANAGER', TIMESTAMP '2025-10-13 21:56:02');

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251014005605_InitialCreate') THEN

    CREATE UNIQUE INDEX `IX_USER_EMAIL` ON `USER` (`EMAIL`);

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251014005605_InitialCreate') THEN

    CREATE INDEX `IX_USER_ROLE_ID_ROLE` ON `USER_ROLE` (`ID_ROLE`);

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251014005605_InitialCreate') THEN

    CREATE INDEX `IX_USER_ROLE_ID_USER` ON `USER_ROLE` (`ID_USER`);

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251014005605_InitialCreate') THEN

    INSERT INTO `__EFMigrationsHistory` (`MIGRATION_ID`, `PRODUCT_VERSION`)
    VALUES ('20251014005605_InitialCreate', '8.0.13');

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

COMMIT;

