CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MIGRATION_ID` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `PRODUCT_VERSION` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EF_MIGRATIONS_HISTORY` PRIMARY KEY (`MIGRATION_ID`)
) CHARACTER SET=utf8mb4;

START TRANSACTION;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20250702020754_InitialCreate') THEN

    ALTER DATABASE CHARACTER SET utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20250702020754_InitialCreate') THEN

    CREATE TABLE `USER` (
        `ID` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        `NAME` VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
        `EMAIL` VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
        `HASH` VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
        `UPDATED_DATE` DATETIME NOT NULL,
        CONSTRAINT `PK_USER` PRIMARY KEY (`ID`)
    ) CHARACTER SET=utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20250702020754_InitialCreate') THEN

    CREATE TABLE `ROLE` (
        `ID` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        `NAME` VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
        `USER_ID` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        `UPDATED_DATE` DATETIME NOT NULL,
        CONSTRAINT `PK_ROLE` PRIMARY KEY (`ID`),
        CONSTRAINT `FK_ROLE_USER_USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
    ) CHARACTER SET=utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20250702020754_InitialCreate') THEN

    CREATE INDEX `IX_ROLE_USER_ID` ON `ROLE` (`USER_ID`);

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20250702020754_InitialCreate') THEN

    CREATE UNIQUE INDEX `IX_USER_EMAIL` ON `USER` (`EMAIL`);

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20250702020754_InitialCreate') THEN

    INSERT INTO `__EFMigrationsHistory` (`MIGRATION_ID`, `PRODUCT_VERSION`)
    VALUES ('20250702020754_InitialCreate', '8.0.13');

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

COMMIT;

