CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MIGRATION_ID` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `PRODUCT_VERSION` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EF_MIGRATIONS_HISTORY` PRIMARY KEY (`MIGRATION_ID`)
) CHARACTER SET=utf8mb4;

START TRANSACTION;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    ALTER DATABASE CHARACTER SET utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    CREATE TABLE `ROLE` (
        `ID` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        `NAME` VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
        `CODE` VARCHAR(10) CHARACTER SET utf8mb4 NOT NULL,
        `UPDATED_DATE` DATETIME NOT NULL,
        CONSTRAINT `PK_ROLE` PRIMARY KEY (`ID`)
    ) CHARACTER SET=utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    CREATE TABLE `USER` (
        `ID` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        `NAME` VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
        `EMAIL` VARCHAR(150) CHARACTER SET utf8mb4 NOT NULL,
        `HASH` VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL,
        `UPDATED_DATE` DATETIME NOT NULL,
        CONSTRAINT `PK_USER` PRIMARY KEY (`ID`)
    ) CHARACTER SET=utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    CREATE TABLE `USER_ROLE` (
        `ID` char(36) COLLATE ascii_general_ci NOT NULL,
        `ID_USER` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        `ID_ROLE` VARCHAR(36) CHARACTER SET utf8mb4 NOT NULL,
        CONSTRAINT `PK_USER_ROLE` PRIMARY KEY (`ID`),
        CONSTRAINT `AK_USER_ROLE_ID_USER_ID_ROLE` UNIQUE (`ID_USER`, `ID_ROLE`),
        CONSTRAINT `FK_USER_ROLE_ROLE_ID_ROLE` FOREIGN KEY (`ID_ROLE`) REFERENCES `ROLE` (`ID`) ON DELETE RESTRICT,
        CONSTRAINT `FK_USER_ROLE_USER_ID_USER` FOREIGN KEY (`ID_USER`) REFERENCES `USER` (`ID`) ON DELETE CASCADE
    ) CHARACTER SET=utf8mb4;

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    INSERT INTO `ROLE` (`ID`, `CODE`, `NAME`, `UPDATED_DATE`)
    VALUES ('da650913-9937-4732-a1e6-86da6ca42d8d', 'UM', 'User Manager', TIMESTAMP '2025-10-19 02:28:06');

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    INSERT INTO `USER` (`ID`, `EMAIL`, `HASH`, `NAME`, `UPDATED_DATE`)
    VALUES ('e8ebb9f7-8c8e-49e8-952d-aaf56e88a055', 'usermanager@gmail.com', '$2a$11$uNGxjs/ErX9ro.1SqQKVOeoANXftn18GFpshWP7XjP.fItQKWY7bm', 'User Manager', TIMESTAMP '2025-10-19 02:28:06');

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    INSERT INTO `USER_ROLE` (`ID`, `ID_ROLE`, `ID_USER`)
    VALUES ('dc22d6be-ae9d-473c-9eda-0567e5952291', 'da650913-9937-4732-a1e6-86da6ca42d8d', 'e8ebb9f7-8c8e-49e8-952d-aaf56e88a055');

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    CREATE UNIQUE INDEX `IX_USER_EMAIL` ON `USER` (`EMAIL`);

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    CREATE INDEX `IX_USER_ROLE_ID_ROLE` ON `USER_ROLE` (`ID_ROLE`);

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    CREATE INDEX `IX_USER_ROLE_ID_USER` ON `USER_ROLE` (`ID_USER`);

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

DROP PROCEDURE IF EXISTS MigrationsScript;
DELIMITER //
CREATE PROCEDURE MigrationsScript()
BEGIN
    IF NOT EXISTS(SELECT 1 FROM `__EFMigrationsHistory` WHERE `MIGRATION_ID` = '20251019022806_InitialCreate') THEN

    INSERT INTO `__EFMigrationsHistory` (`MIGRATION_ID`, `PRODUCT_VERSION`)
    VALUES ('20251019022806_InitialCreate', '8.0.13');

    END IF;
END //
DELIMITER ;
CALL MigrationsScript();
DROP PROCEDURE MigrationsScript;

COMMIT;

