// <auto-generated />
using System;
using AuthApi.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthApi.Infraestructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20251016021507_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("CODE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK_ROLE");

                    b.ToTable("ROLE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "33333333-3333-3333-3333-333333333333",
                            Code = "MASTER",
                            Name = "MASTER",
                            UpdatedDate = new DateTime(2025, 10, 16, 2, 15, 7, 195, DateTimeKind.Utc).AddTicks(6131)
                        },
                        new
                        {
                            Id = "11111111-1111-1111-1111-111111111111",
                            Code = "ADMIN",
                            Name = "ADMIN",
                            UpdatedDate = new DateTime(2025, 10, 16, 2, 15, 7, 195, DateTimeKind.Utc).AddTicks(6133)
                        },
                        new
                        {
                            Id = "22222222-2222-2222-2222-222222222222",
                            Code = "USER",
                            Name = "USER",
                            UpdatedDate = new DateTime(2025, 10, 16, 2, 15, 7, 195, DateTimeKind.Utc).AddTicks(6135)
                        });
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("HASH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK_USER");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USER_EMAIL");

                    b.ToTable("USER", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "44444444-4444-4444-4444-444444444444",
                            Email = "admin@authapi.com",
                            Hash = "BCrypt.Net.BCrypt.HashPassword(admin123)",
                            Name = "Administrador",
                            UpdatedDate = new DateTime(2025, 10, 16, 2, 15, 7, 195, DateTimeKind.Utc).AddTicks(6259)
                        },
                        new
                        {
                            Id = "55555555-5555-5555-5555-555555555555",
                            Email = "user@authapi.com",
                            Hash = "BCrypt.Net.BCrypt.HashPassword(admin123)",
                            Name = "Usuário Padrão",
                            UpdatedDate = new DateTime(2025, 10, 16, 2, 15, 7, 195, DateTimeKind.Utc).AddTicks(6261)
                        },
                        new
                        {
                            Id = "66666666-6666-6666-6666-666666666666",
                            Email = "master@authapi.com",
                            Hash = "BCrypt.Net.BCrypt.HashPassword(admin123)",
                            Name = "Gerente",
                            UpdatedDate = new DateTime(2025, 10, 16, 2, 15, 7, 195, DateTimeKind.Utc).AddTicks(6263)
                        });
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("IdRole")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID_ROLE");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id")
                        .HasName("PK_USER_ROLE");

                    b.HasAlternateKey("IdUser", "IdRole")
                        .HasName("AK_USER_ROLE_ID_USER_ID_ROLE");

                    b.HasIndex("IdRole")
                        .HasDatabaseName("IX_USER_ROLE_ID_ROLE");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("IX_USER_ROLE_ID_USER");

                    b.ToTable("USER_ROLE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            IdRole = "11111111-1111-1111-1111-111111111111",
                            IdUser = "44444444-4444-4444-4444-444444444444"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            IdRole = "22222222-2222-2222-2222-222222222222",
                            IdUser = "55555555-5555-5555-5555-555555555555"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            IdRole = "33333333-3333-3333-3333-333333333333",
                            IdUser = "66666666-6666-6666-6666-666666666666"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            IdRole = "22222222-2222-2222-2222-222222222222",
                            IdUser = "66666666-6666-6666-6666-666666666666"
                        });
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.UserRole", b =>
                {
                    b.HasOne("AuthApi.Infraestructure.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE_ROLE_ID_ROLE");

                    b.HasOne("AuthApi.Infraestructure.Domain.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE_USER_ID_USER");
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
