// <auto-generated />
using System;
using AuthApi.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthApi.Infraestructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20250713214941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("CHAR(1)")
                        .HasColumnName("CODE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK_ROLE");

                    b.ToTable("ROLE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6b4441ca-a23a-4ec4-b3bd-a1ca1507d9de",
                            Code = "A",
                            Name = "ADMIN",
                            UpdatedDate = new DateTime(2025, 7, 13, 18, 49, 40, 298, DateTimeKind.Local).AddTicks(2366)
                        },
                        new
                        {
                            Id = "2e355313-89d3-4274-a25b-e1ffe372dfbb",
                            Code = "U",
                            Name = "USER",
                            UpdatedDate = new DateTime(2025, 7, 13, 18, 49, 40, 298, DateTimeKind.Local).AddTicks(2409)
                        },
                        new
                        {
                            Id = "4535ace9-c485-4c16-b086-3f7b3f48a08b",
                            Code = "M",
                            Name = "MANAGER",
                            UpdatedDate = new DateTime(2025, 7, 13, 18, 49, 40, 298, DateTimeKind.Local).AddTicks(2411)
                        });
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("HASH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK_USER");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USER_EMAIL");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("IdRole")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID_ROLE");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id")
                        .HasName("PK_USER_ROLE");

                    b.HasIndex("IdRole")
                        .HasDatabaseName("IX_USER_ROLE_ID_ROLE");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("IX_USER_ROLE_ID_USER");

                    b.ToTable("USER_ROLE", (string)null);
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.UserRole", b =>
                {
                    b.HasOne("AuthApi.Infraestructure.Domain.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE_USER_ID_USER");
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
