// <auto-generated />
using System;
using AuthApi.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthApi.Infraestructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20251019022806_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("CODE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK_ROLE");

                    b.ToTable("ROLE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "da650913-9937-4732-a1e6-86da6ca42d8d",
                            Code = "UM",
                            Name = "User Manager",
                            UpdatedDate = new DateTime(2025, 10, 19, 2, 28, 6, 233, DateTimeKind.Utc).AddTicks(3848)
                        });
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("HASH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK_USER");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USER_EMAIL");

                    b.ToTable("USER", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "e8ebb9f7-8c8e-49e8-952d-aaf56e88a055",
                            Email = "usermanager@gmail.com",
                            Hash = "$2a$11$uNGxjs/ErX9ro.1SqQKVOeoANXftn18GFpshWP7XjP.fItQKWY7bm",
                            Name = "User Manager",
                            UpdatedDate = new DateTime(2025, 10, 19, 2, 28, 6, 233, DateTimeKind.Utc).AddTicks(3971)
                        });
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<string>("IdRole")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID_ROLE");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id")
                        .HasName("PK_USER_ROLE");

                    b.HasAlternateKey("IdUser", "IdRole")
                        .HasName("AK_USER_ROLE_ID_USER_ID_ROLE");

                    b.HasIndex("IdRole")
                        .HasDatabaseName("IX_USER_ROLE_ID_ROLE");

                    b.HasIndex("IdUser")
                        .HasDatabaseName("IX_USER_ROLE_ID_USER");

                    b.ToTable("USER_ROLE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc22d6be-ae9d-473c-9eda-0567e5952291"),
                            IdRole = "da650913-9937-4732-a1e6-86da6ca42d8d",
                            IdUser = "e8ebb9f7-8c8e-49e8-952d-aaf56e88a055"
                        });
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.UserRole", b =>
                {
                    b.HasOne("AuthApi.Infraestructure.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE_ROLE_ID_ROLE");

                    b.HasOne("AuthApi.Infraestructure.Domain.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE_USER_ID_USER");
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
