// <auto-generated />
using System;
using AuthApi.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthApi.Infraestructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20250702020754_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_ROLE");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ROLE_USER_ID");

                    b.ToTable("ROLE", (string)null);
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("HASH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("NAME");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("Id")
                        .HasName("PK_USER");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_USER_EMAIL");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.Role", b =>
                {
                    b.HasOne("AuthApi.Infraestructure.Domain.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ROLE_USER_USER_ID");
                });

            modelBuilder.Entity("AuthApi.Infraestructure.Domain.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
